Bump nokogiri from 1.13.6 to 1.13.9 (#10)
* Bump nokogiri from 1.13.6 to 1.13.9

Bumps [nokogiri](https://github.com/sparklemotion/nokogiri) from 1.13.6 to 1.13.9.
- [Release notes](https://github.com/sparklemotion/nokogiri/releases)
- [Changelog](https://github.com/sparklemotion/nokogiri/blob/main/CHANGELOG.md)
- [Commits](https://github.com/sparklemotion/nokogiri/compare/v1.13.6...v1.13.9)

---
updated-dependencies:
- dependency-name: nokogiri
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

* Correct Ruby version syntax in Gemfile

br3ndonland/br3ndonland.github.io#10

Vercel build error:

```text
Your Ruby patchlevel is 0, but your Gemfile specified -1
Error: Command "bundle install" exited with 18
```

* Delete Gemfile.lock

Bundler cannot install the project, either in CI or on macOS locally,
due to errors when installing nokogiri and eventmachine.

---------

Signed-off-by: dependabot[bot] <support@github.com>